#!/bin/bash
#A -> add (git add .)
#M -> modificados (diffs)
#?? -> agregados
dir="$(dirname "$0")"
getColor="/tmp/ckbcolor"
[ ! -f $getColor ] && touch $getColor
function setColor {
	local ckbpipe="/tmp/ckbpipe012"
	echo "rgb $1$2" > $ckbpipe	
}

function isGit { 
  [ -d .git ] || git rev-parse --git-dir 2> /dev/null 1> /dev/null
  #git rev-parse is-inside-work-tree
  #if [ -d .git ]; then
  #  echo .git;
  #else
  #  git rev-parse --git-dir 2> /dev/null 1> /dev/null;
  #fi;
}

alpha="FF"
color="FFFFFF"
isGit
if [ $? -eq 0 ]; then
	gs=$(git status --porcelain | grep '^A\|^\sM\|^??')
	if [ $? -eq 0 ]; then
		color="FF7E00"
	else
		color="73D216"
	fi
fi
if [[ ! $(cat $getColor) == $color ]]; then
	echo $color > $getColor
	setColor $color $alpha
fi

